---
title: "Análisis Encuesta"
author: "Alberto Rodríguez R"
date: '2022-06-24'
output: 
  word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
body {
  font-family: "Noto Sans", sans-serif; 
  font-size: 1.5rem;
  text-align: justify;
}
```

```{r, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(scales)
```


```{r, echo=FALSE, eval=TRUE}
# Importar y transformar datos

ProyectoB <- read_excel("Datos/Fuentes/Encuesta ProyectoB.xlsx")

# Crear factores

ProyectoB$Pregunta1 <- factor(ProyectoB$Pregunta1, levels = c("Sí", "Tal vez", "No"))
ProyectoB$Pregunta2 <- factor(ProyectoB$Pregunta2, levels = c("Sí", "Tal vez", "No"))
ProyectoB$Pregunta3 <- factor(ProyectoB$Pregunta3, levels = c("Sí", "No"))
ProyectoB$Pregunta4 <- factor(ProyectoB$Pregunta4, levels = c("Sí", "Tal vez", "No"))
ProyectoB$Pregunta5 <- factor(ProyectoB$Pregunta5, levels = c("Sí", "No"))
```

# Gráfico General

```{r, echo=FALSE, eval=TRUE}
percentData <- ProyectoB %>%  pivot_longer(Pregunta1:Pregunta5, 
                           names_to = "Preguntas", 
                           values_to = "Respuestas") %>% 
                           group_by(Preguntas) %>% count(Respuestas) %>%
    mutate(N = n/sum(n),
           ratio=scales::percent(n/sum(n)))

ProyectoB %>% pivot_longer(Pregunta1:Pregunta5, 
                           names_to = "Preguntas", 
                           values_to = "Respuestas") %>% 
  ggplot(aes(x = Preguntas, fill = Respuestas))+
  geom_bar(position = position_fill(reverse = TRUE)) + 
  labs(x = " \nPreguntas",
       y = "Porcentaje")+
  geom_hline(yintercept=0.7, col = "blue", linetype="dashed", size = 1.3)+
  scale_y_continuous(limits=c(0, 1),
                      breaks = seq(0, 1, .2),
                     label = c('0%', '20%', '40%', '60%', '80%', '100%')) +
    geom_text(data=percentData, aes(y=N,label=ratio),
              position = position_fill(vjust = 0.5, reverse = TRUE))+
  theme(legend.position = "bottom")+
  scale_fill_manual(values = c("#7fc97f", "#beaed4", "#fdc086"))
```

## Gráfico Monto Inversión

```{r, echo=FALSE, eval=TRUE}
GPreg6 <- ProyectoB %>% 
  group_by(Pregunta6) %>%
  summarize(Total = n()) %>% 
  mutate(pct = Total/sum(Total),
         Porcentaje = scales::percent(pct))

# Gráfico de Barras

ggplot(GPreg6, aes(x = Pregunta6, y=pct)) + 
  geom_bar(stat = 'identity', fill = "#74c476")+
    scale_y_continuous(limits=c(0, 1), 
                     breaks = seq(0, 1, .2), 
                     label = c('0%', '20%', '40%', '60%', '80%', '100%')) +
 scale_x_discrete(labels = label_wrap(12)) +
  geom_text(aes(label = Porcentaje), 
            size = 4, 
            position = position_stack(vjust = 1.1))+
    xlab("\n ¿Cuánto estaría dispuesto a invertir?") + 
  ylab("Porcentaje")
  # theme_stata() +
  # theme(
  #   axis.title.x = element_text(color="black", size=13, face="bold"),
  #   axis.title.y = element_text(color="black", size=13, face="bold" ),
  #   legend.title = element_text(colour="blue", size=10, face="bold", vjust = 0.7))
```

